# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyTiff.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(50, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageFrame = QtWidgets.QFrame(self.Main)
        self.imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageFrame.setObjectName("imageFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.imageFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QVBoxLayout()
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addLayout(self.graphicsView)
        self.bandSelectBox = QtWidgets.QComboBox(self.imageFrame)
        self.bandSelectBox.setObjectName("bandSelectBox")
        self.bandSelectBox.addItem("")
        self.verticalLayout_2.addWidget(self.bandSelectBox)
        self.horizontalLayout_2.addWidget(self.imageFrame)
        self.infoFrame = QtWidgets.QFrame(self.Main)
        self.infoFrame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.infoFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.infoFrame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(self.infoFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.filePathText = QtWidgets.QLineEdit(self.infoFrame)
        self.filePathText.setObjectName("filePathText")
        self.verticalLayout.addWidget(self.filePathText)
        self.label_3 = QtWidgets.QLabel(self.infoFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.fileGeoLocationX = QtWidgets.QLineEdit(self.infoFrame)
        self.fileGeoLocationX.setReadOnly(False)
        self.fileGeoLocationX.setObjectName("fileGeoLocationX")
        self.verticalLayout.addWidget(self.fileGeoLocationX)
        self.fileGeoLocationY = QtWidgets.QLineEdit(self.infoFrame)
        self.fileGeoLocationY.setReadOnly(False)
        self.fileGeoLocationY.setObjectName("fileGeoLocationY")
        self.verticalLayout.addWidget(self.fileGeoLocationY)
        self.label_4 = QtWidgets.QLabel(self.infoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.fileGeoLocationLat = QtWidgets.QLineEdit(self.infoFrame)
        self.fileGeoLocationLat.setObjectName("fileGeoLocationLat")
        self.verticalLayout.addWidget(self.fileGeoLocationLat)
        self.fileGeoLocationLon = QtWidgets.QLineEdit(self.infoFrame)
        self.fileGeoLocationLon.setObjectName("fileGeoLocationLon")
        self.verticalLayout.addWidget(self.fileGeoLocationLon)
        self.line = QtWidgets.QFrame(self.infoFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.infoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.actionViewGeodetics = QtWidgets.QPushButton(self.infoFrame)
        self.actionViewGeodetics.setObjectName("actionViewGeodetics")
        self.verticalLayout.addWidget(self.actionViewGeodetics)
        self.label_7 = QtWidgets.QLabel(self.infoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.actionViewCameraInfo = QtWidgets.QPushButton(self.infoFrame)
        self.actionViewCameraInfo.setObjectName("actionViewCameraInfo")
        self.verticalLayout.addWidget(self.actionViewCameraInfo)
        self.logView = QtWidgets.QTextEdit(self.infoFrame)
        self.logView.setObjectName("logView")
        self.verticalLayout.addWidget(self.logView)
        self.horizontalLayout_2.addWidget(self.infoFrame)
        self.tabWidget.addTab(self.Main, "")
        self.Calibration = QtWidgets.QWidget()
        self.Calibration.setObjectName("Calibration")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Calibration)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calibrationGraphicsView = QtWidgets.QVBoxLayout()
        self.calibrationGraphicsView.setObjectName("calibrationGraphicsView")
        self.horizontalLayout.addLayout(self.calibrationGraphicsView)
        self.frame = QtWidgets.QFrame(self.Calibration)
        self.frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.calPathText = QtWidgets.QLineEdit(self.frame)
        self.calPathText.setObjectName("calPathText")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.calPathText)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_4)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_5)
        self.redValText = QtWidgets.QLineEdit(self.frame)
        self.redValText.setObjectName("redValText")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.redValText)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.blueValText = QtWidgets.QLineEdit(self.frame)
        self.blueValText.setObjectName("blueValText")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.blueValText)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.greenValText = QtWidgets.QLineEdit(self.frame)
        self.greenValText.setObjectName("greenValText")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.greenValText)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.redEdgeValText = QtWidgets.QLineEdit(self.frame)
        self.redEdgeValText.setObjectName("redEdgeValText")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.redEdgeValText)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.nearInfraredValText = QtWidgets.QLineEdit(self.frame)
        self.nearInfraredValText.setObjectName("nearInfraredValText")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.nearInfraredValText)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.panelRadianceText = QtWidgets.QLineEdit(self.frame)
        self.panelRadianceText.setObjectName("panelRadianceText")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.panelRadianceText)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.line_6)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.line_7)
        self.panelCornerText = QtWidgets.QLineEdit(self.frame)
        self.panelCornerText.setObjectName("panelCornerText")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.panelCornerText)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.label_18)
        self.actionViewCalPlots = QtWidgets.QPushButton(self.frame)
        self.actionViewCalPlots.setObjectName("actionViewCalPlots")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.actionViewCalPlots)
        self.horizontalLayout.addWidget(self.frame)
        self.tabWidget.addTab(self.Calibration, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProcess = QtWidgets.QMenu(self.menubar)
        self.menuProcess.setObjectName("menuProcess")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionImport_Directory = QtWidgets.QAction(MainWindow)
        self.actionImport_Directory.setObjectName("actionImport_Directory")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionAdd_Band = QtWidgets.QAction(MainWindow)
        self.actionAdd_Band.setObjectName("actionAdd_Band")
        self.actionRadiance_to_Reflectance = QtWidgets.QAction(MainWindow)
        self.actionRadiance_to_Reflectance.setObjectName("actionRadiance_to_Reflectance")
        self.actionImport_Calibration_Panel = QtWidgets.QAction(MainWindow)
        self.actionImport_Calibration_Panel.setObjectName("actionImport_Calibration_Panel")
        self.actionChange_Resolution_Value = QtWidgets.QAction(MainWindow)
        self.actionChange_Resolution_Value.setObjectName("actionChange_Resolution_Value")
        self.actionExport_Image = QtWidgets.QAction(MainWindow)
        self.actionExport_Image.setObjectName("actionExport_Image")
        self.actionMerge_Bands_to_Raster = QtWidgets.QAction(MainWindow)
        self.actionMerge_Bands_to_Raster.setObjectName("actionMerge_Bands_to_Raster")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionImport_Calibration_Panel)
        self.menuFile.addAction(self.actionReset)
        self.menuProcess.addAction(self.actionAdd_Band)
        self.menuProcess.addAction(self.actionRadiance_to_Reflectance)
        self.menuProcess.addSeparator()
        self.menuProcess.addAction(self.actionMerge_Bands_to_Raster)
        self.menuProcess.addSeparator()
        self.menuProcess.addAction(self.actionChange_Resolution_Value)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProcess.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bandSelectBox.setItemText(0, _translate("MainWindow", "Band 1"))
        self.label_5.setText(_translate("MainWindow", "Metadata"))
        self.label_2.setText(_translate("MainWindow", "File Name"))
        self.label_3.setText(_translate("MainWindow", "Geo-Location (XY)"))
        self.label_4.setText(_translate("MainWindow", "Geo-Location (Lat, Lon)"))
        self.label_6.setText(_translate("MainWindow", "Geodetics"))
        self.actionViewGeodetics.setText(_translate("MainWindow", "View Geodetic Information"))
        self.label_7.setText(_translate("MainWindow", "Camera"))
        self.actionViewCameraInfo.setText(_translate("MainWindow", "View Camera Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("MainWindow", "Main"))
        self.label_9.setText(_translate("MainWindow", "Calibration Image Path"))
        self.label_10.setText(_translate("MainWindow", "Band Calibration Values "))
        self.label_11.setText(_translate("MainWindow", "Red"))
        self.label_12.setText(_translate("MainWindow", "Blue"))
        self.label_13.setText(_translate("MainWindow", "Green"))
        self.label_14.setText(_translate("MainWindow", "Red Edge"))
        self.label_15.setText(_translate("MainWindow", "Near Infrared"))
        self.label_16.setText(_translate("MainWindow", "Panel Information"))
        self.label_17.setText(_translate("MainWindow", "Mean Panel Radiance"))
        self.label_18.setText(_translate("MainWindow", "Panel Corners"))
        self.actionViewCalPlots.setText(_translate("MainWindow", "View Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibration), _translate("MainWindow", "Calibration"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProcess.setTitle(_translate("MainWindow", "Process"))
        self.actionImport.setText(_translate("MainWindow", "Import Single File"))
        self.actionImport_Directory.setText(_translate("MainWindow", "Import Directory"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionAdd_Band.setText(_translate("MainWindow", "Add Band"))
        self.actionRadiance_to_Reflectance.setText(_translate("MainWindow", "Radiance to Reflectance"))
        self.actionImport_Calibration_Panel.setText(_translate("MainWindow", "Import Calibration Panel"))
        self.actionChange_Resolution_Value.setText(_translate("MainWindow", "Change Resolution Value"))
        self.actionExport_Image.setText(_translate("MainWindow", "Export Image..."))
        self.actionMerge_Bands_to_Raster.setText(_translate("MainWindow", "Merge Bands to Raster"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

